version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: on-failure

  mongoseed:
    image: mongo
    links:
      - mongodb 
    volumes:
      - ./mongodb/:/mongodb
    command: mongoimport --host mongodb --db indep --collection estate --file /mongodb/datos.json --jsonArray
  
  api:
    container_name: api
    build: .
    ports: 
      - "5000:5000"
    links:
      - mongodb
    restart: on-failure
